/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ben
 */

public class Calculator_GUI extends javax.swing.JFrame {
    final static double[] OFFSET_LUT = {-1.5,-1.6,-1.7,-1.8,-1.9,-2,-2.1,-2.2,-2.3,-2.4,-2.5,-2.45,-2.4,-2.35,-2.3,-2.25,-2.2,-2.15,-2.1,-2.05,-2,-1.6,-1.2,-0.8,-0.4,0,0.4,0.8,1.2,1.6,2,2.7,3.4,4.1,4.8,5.5,6.2,6.9,7.6,8.3,9,8.85,8.7,8.55,8.4,8.25,8.1,7.95,7.8,7.65,7.5,7.4,7.3,7.2,7.1,7,6.9,6.8,6.7,6.6,6.5,6.55,6.6,6.65,6.7,6.75,6.8,6.85,6.9,6.95,7,7.25,7.5,7.75,8,8.25,8.5,8.75,9,9.25,9.5,9.45,9.4,9.35,9.3,9.25,9.2,9.15,9.1,9.05,9,8.95,8.9,8.85,8.8,8.75,8.7,8.65,8.6,8.55,8.5,8.5,8.5,8.5,8.5,8.5,8.5,8.5,8.5,8.5,8.5,8.4,8.3,8.2,8.1,8,7.9,7.8,7.7,7.6,7.5,7.35,7.2,7.05,6.9,6.75,6.6,6.45,6.3,6.15,6,5.9,5.8,5.7,5.6,5.5,5.4,5.3,5.2,5.1,5,4.65,4.3,3.95,3.6,3.25,2.9,2.55,2.2,1.85,1.5,1.25,1,0.75,0.5,0.25,-3.55E-15,-0.25,-0.5,-0.75,-1,-1.05,-1.1,-1.15,-1.2,-1.25,-1.3,-1.35,-1.4,-1.45,-1.5,-1.6,-1.7,-1.8,-1.9,-2,-2.1,-2.2,-2.3,-2.4,-2.5,-2.2,-1.9,-1.6,-1.3,-1,-0.7,-0.4,-0.1,0.2,0.5,0.65,0.8,0.95,1.1,1.25,1.4,1.55,1.7,1.85,2,2.25,2.5,2.75,3,3.25,3.5,3.75,4,4.25,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.6,4.7,4.8,4.9,5,5.1,5.2,5.3,5.4,5.5,5.65,5.8,5.95,6.1,6.25,6.4,6.55,6.7,6.85,7,6.95,6.9,6.85,6.8,6.75,6.7,6.65,6.6,6.55,6.5,6.6,6.7,6.8,6.9,7,7.1,7.2,7.3,7.4,7.5,7.45,7.4,7.35,7.3,7.25,7.2,7.15,7.1,7.05,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12,12.45,12.9,13.35,13.8,14.25,14.7,15.15,15.6,16.05,16.5,16.6,16.7,16.8,16.9,17,17.1,17.2,17.3,17.4,17.5,17.6,17.7,17.8,17.9,18,18.1,18.2,18.3,18.4,18.5,18.9,19.3,19.7,20.1,20.5,20.9,21.3,21.7,22.1,22.5,23.35,24.2,25.05,25.9,26.75,27.6,28.45,29.3,30.15,31,31.5,32,32.5,33,33.5,34,34.5,35,35.5,36,36.35,36.7,37.05,37.4,37.75,38.1,38.45,38.8,39.15,39.5,40.55,41.6,42.65,43.7,44.75,45.8,46.85,47.9,48.95,50,50.5,51,51.5,52,52.5,53,53.5,54,54.5,55};

    /**
     * Creates new form Calculator_GUI
     */
    public Calculator_GUI() {
        //Initialize the voltage offset array LUT (index 0 = 680nm, index 370 = 1050nm)
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        WavelengthLabel = new javax.swing.JLabel();
        WavelengthBox = new javax.swing.JTextField();
        PowerBox = new javax.swing.JTextField();
        PowerLabel = new javax.swing.JLabel();
        CalculatePowerButton = new javax.swing.JButton();
        ResultLabel = new javax.swing.JLabel();
        CalculateVoltageButton = new javax.swing.JButton();
        VoltageBox = new javax.swing.JTextField();
        VoltageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        calibrationMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        calibrationHelp = new javax.swing.JMenuItem();
        calculatorHelp = new javax.swing.JMenuItem();
        aboutHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Pockels Cell Voltage Calculator");

        WavelengthLabel.setText("Laser wavelenth (680nm - 1050nm)");

        WavelengthBox.setText("950");
        WavelengthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WavelengthBoxActionPerformed(evt);
            }
        });

        PowerBox.setText("10");
        PowerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerBoxActionPerformed(evt);
            }
        });

        PowerLabel.setText("Percent output power (0-100%)");

        CalculatePowerButton.setText("Calculate Power");
        CalculatePowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatePowerButtonActionPerformed(evt);
            }
        });

        ResultLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        CalculateVoltageButton.setText("Calculate Voltage");
        CalculateVoltageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateVoltageButtonActionPerformed(evt);
            }
        });

        VoltageBox.setText("80");

        VoltageLabel.setText("Pockels Cell Voltage");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pockels_Image/Pockels Image - applet2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CalculatePowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CalculateVoltageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VoltageBox)
                            .addComponent(PowerBox)
                            .addComponent(WavelengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VoltageLabel)
                            .addComponent(WavelengthLabel)
                            .addComponent(PowerLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WavelengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WavelengthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoltageLabel))
                .addGap(18, 18, 18)
                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateVoltageButton)
                    .addComponent(CalculatePowerButton))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TitleLabel)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        calibrationMenu.setText("Calibration");

        jMenuItem1.setText("Run Calibration Wizard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        calibrationMenu.add(jMenuItem1);

        jMenuItem4.setText("View Calibration Data");
        calibrationMenu.add(jMenuItem4);

        jMenuItem3.setText("Import Calibration File");
        calibrationMenu.add(jMenuItem3);

        jMenuItem2.setText("Check Date of Last Calibration");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        calibrationMenu.add(jMenuItem2);

        jMenuBar1.add(calibrationMenu);

        helpMenu.setText("Help");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });

        calibrationHelp.setText("Calibration");
        calibrationHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibrationHelpActionPerformed(evt);
            }
        });
        helpMenu.add(calibrationHelp);

        calculatorHelp.setText("Calculator");
        helpMenu.add(calculatorHelp);

        aboutHelp.setText("About");
        aboutHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutHelpActionPerformed(evt);
            }
        });
        helpMenu.add(aboutHelp);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void calibrationHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibrationHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calibrationHelpActionPerformed

    private void CalculateVoltageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateVoltageButtonActionPerformed
        //Import information from the two text boxes
        int wavelength = (int)(Double.parseDouble(WavelengthBox.getText()));
        double power = (Double.parseDouble(PowerBox.getText()));

        //Get the offset that corresponds to the input wavelength
        double offset = OFFSET_LUT[wavelength-680];

        //Calculate the appropriate voltage using a sine wave approximation
        double voltPeriod = 0.777*wavelength-21.537; //Equation derived from trendline of measured data R^2 = 0.996
        int voltagePockels = (int)Math.round((Math.asin(power/50-1) + Math.PI/2)*(voltPeriod/(2*Math.PI)) + offset);

        //Output the result
        ResultLabel.setText("Pockels Voltage = " + voltagePockels + " Volts");
        VoltageBox.setText(""+voltagePockels);
    }//GEN-LAST:event_CalculateVoltageButtonActionPerformed

    private void CalculatePowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatePowerButtonActionPerformed
        //Import information from the two text boxes
        int wavelength = (int)(Double.parseDouble(WavelengthBox.getText()));
        double voltage = (Double.parseDouble(VoltageBox.getText()));

        //Get the offset that corresponds to the input wavelength
        double offset = OFFSET_LUT[wavelength-680];

        //Calculate the corresponding power using a sine wave approximation
        double voltPeriod = 0.777*wavelength-21.537; //Equation derived from trendline of measured data R^2 = 0.996
        double voltPhase = ((voltPeriod/4 + offset)/voltPeriod)*2D*Math.PI;
        int laserPower = (int) Math.round(Math.sin(2*Math.PI/voltPeriod*voltage-voltPhase)*50+50);
        //Output the result
        ResultLabel.setText("Laser Power Output = " + laserPower + "%");
        PowerBox.setText(""+laserPower);

    }//GEN-LAST:event_CalculatePowerButtonActionPerformed

    private void PowerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerBoxActionPerformed

    private void WavelengthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WavelengthBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WavelengthBoxActionPerformed

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuActionPerformed

    private void aboutHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutHelpActionPerformed
        aboutPackage.aboutFrame about = new aboutPackage.aboutFrame();
        about.setVisible(true);
    }//GEN-LAST:event_aboutHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculatePowerButton;
    private javax.swing.JButton CalculateVoltageButton;
    private javax.swing.JTextField PowerBox;
    private javax.swing.JLabel PowerLabel;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField VoltageBox;
    private javax.swing.JLabel VoltageLabel;
    private javax.swing.JTextField WavelengthBox;
    private javax.swing.JLabel WavelengthLabel;
    private javax.swing.JMenuItem aboutHelp;
    private javax.swing.JMenuItem calculatorHelp;
    private javax.swing.JMenuItem calibrationHelp;
    private javax.swing.JMenu calibrationMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
